Merge develop (#334)
* APIS-878: Merchant user login/logout endpoint (#317)

* APIS-878: Merchant user login endpoint

* APIS-878: Added merchant user logout endpoint

* APIS-878: CR comments

* Fix Smaug call (#321)

* Added the public prefix for the public api routes (#318)

* Added the public prefix for the public api routes

* Changed the name back to the normal one

* Switch two tests to public prefix

* APIS-829: Added dunning status to order response (#320)

* APIS-829: Added dunning status to order response

* APIS-829: Remove duplicate status

* APIS-829: Lazy load order dunning status

* APIS-829: Add missing order amounts in order response

* Add missing controllers to the public namespace (#323)

* Add missing public controllers to the PublicApi namespace

* Fix OpenApi annotaion

* Change pause dunning endpoint success response to 204

* Fix security firewalls to include the optional /public prefix

* simplify API docs generation (#324)

* refactor seeder and detect if merchant already exists. (#328)

* Add missing debtor external data address city to order response (#326)

* Add missing debtor external data address city to order response

* Fixed typo

* Fix to retrieve invoice data when order is in state complete (#331)

* Fix fully paid dunning state (#333)

diff --git a/bin/redoc-bundle b/bin/redoc-bundle
--- a/bin/redoc-bundle
+++ b/bin/redoc-bundle
@@ -1,46 +1,17 @@
 #!/usr/bin/env bash
 
-command -v git >/dev/null 2>&1 || {
-    echo "ERROR: git is not installed. Aborting..."
+command -v npx >/dev/null 2>&1 || {
+    echo "ERROR: npm / npx are not installed. Aborting API docs generation..."
     exit 1
 }
 
-command -v tar >/dev/null 2>&1 || {
-    echo "ERROR: tar is not installed. Aborting..."
-    exit 1
-}
+BILLIE_ORANGE_COLOR="#ff4338"
+BILLIE_BLUE_COLOR="#1f2530"
+TEXT_COLOR=${BILLIE_BLUE_COLOR}
+TEXT_SECONDARY_COLOR="#505f7c"
+SUCCESS_COLOR="#6bbd5b"
+ERROR_COLOR="#ED6456"
 
-if [[ ! -d ./.git ]]; then
-    echo "Current working dir '${PWD}' is not a git repository. Aborting..."
-    exit 1
-fi
-
-command -v redoc-cli >/dev/null 2>&1 || {
-    echo "ERROR: redoc-cli is not installed. Aborting..."
-    exit 1
-}
-
-SPEC_VERSION=$(git describe --tags --abbrev=0 || echo "dev")
-SPEC_PREV_VERSION=$(git describe --tags --abbrev=0 --exclude=$(git describe --tags --abbrev=0))
-
-if [[ $1 = "public" ]]; then
-   TITLE="Billie - PaD API Documentation"
-   SPEC_FILE=${2:-"paella-${SPEC_VERSION}-openapi.yaml"}
-else
-   TITLE="Billie - PaD-Core API Documentation"
-   SPEC_FILE=${2:-"paella-${SPEC_VERSION}-openapi-internal.yaml"}
-fi
-
-if [[ -f "docs/openapi/${SPEC_FILE}" ]]; then
-    # Do not override existing spec if same tag
-    SPEC_VERSION="${SPEC_VERSION}-dev"
-    SPEC_FILE=${SPEC_FILE/-openapi.yaml/-dev-openapi.yaml}
-    SPEC_FILE=${SPEC_FILE/-openapi-internal.yaml/-dev-openapi-internal.yaml}
-fi
-
-PRIMARY_COLOR="#ff4338"
-SECONDARY_COLOR="#1f2530"
-TEXT_COLOR=${SECONDARY_COLOR}
 LOGO_PADDING="40px"
 LOGO_MAX_HEIGHT="160px"
 MAIN_FONT="Roboto, Helvetica, sans-serif"
@@ -48,42 +19,52 @@ HEADING_FONT="Monserrat, Helvetica, sans-serif"
 HEADING_FONT_WEIGHT="bold"
 VERTICAL_SPACING="20"
 
+SPEC_GROUP=${1:-"public"}
+SPEC_VERSION=${2:-$(git describe --tags 2> /dev/null || echo "dev")}
+SPEC_FILE="paella-openapi-${SPEC_GROUP}.yaml"
 
-echo "Generation YAML specification (version: ${SPEC_VERSION})..."
-
-OA_GENERATED=1
-
-if [[ $1 = "public" ]]; then
-   bin/console paella:openapi:generate ${SPEC_VERSION} --output-file="docs/openapi/${SPEC_FILE}" --title="${TITLE}" --groups=public || OA_GENERATED=0
+if [[ ${SPEC_GROUP} = "public" ]]; then
+   SPEC_TITLE="Billie - PaD API Documentation"
 else
-   bin/console paella:openapi:generate ${SPEC_VERSION} --output-file="docs/openapi/${SPEC_FILE}" --title="${TITLE}" || OA_GENERATED=0
+   SPEC_TITLE="Billie - PaD API Documentation (${SPEC_GROUP})"
 fi
 
-echo "Generating HTML documentation (version: ${SPEC_VERSION})..."
-redoc-cli bundle "docs/openapi/${SPEC_FILE}" --options.theme.colors.primary.main="${PRIMARY_COLOR}" \
---options.theme.rightPanel.backgroundColor="${SECONDARY_COLOR}" --options.theme.logo.gutter="${LOGO_PADDING}" \
---options.theme.logo.maxHeight="${LOGO_MAX_HEIGHT}" --title="${TITLE}" \
+echo "Generating API YAML specification (version: ${SPEC_VERSION})..."
+
+mkdir -p docs/openapi
+rm -f docs/openapi/${SPEC_FILE}
+
+bin/console paella:openapi:generate ${SPEC_VERSION} \
+        --output-file="docs/openapi/${SPEC_FILE}" --title="${SPEC_TITLE}" --groups=${SPEC_GROUP}
+
+if [[ ! -f docs/openapi/${SPEC_FILE} ]]; then
+    echo "ERROR: Open API generation failed. Spec. file does not exist."
+    exit 1;
+fi
+
+echo "Generating API HTML documentation (version: ${SPEC_VERSION})..."
+
+SPEC_HTML_FILE=docs/openapi/${SPEC_FILE/yaml/html}
+rm -f ${SPEC_HTML_FILE}
+
+npx redoc-cli bundle "docs/openapi/${SPEC_FILE}" \
+--title="${SPEC_TITLE}" \
+--options.theme.colors.primary.main="${BILLIE_ORANGE_COLOR}" \
+--options.theme.rightPanel.backgroundColor="${BILLIE_BLUE_COLOR}" \
+--options.theme.colors.text.primary="${TEXT_COLOR}" \
+--options.theme.colors.text.secondary="${TEXT_SECONDARY_COLOR}" \
+--options.theme.colors.success.main="${SUCCESS_COLOR}" \
+--options.theme.colors.error.main="${ERROR_COLOR}" \
+--options.theme.logo.gutter="${LOGO_PADDING}" \
+--options.theme.logo.maxHeight="${LOGO_MAX_HEIGHT}" \
 --options.theme.typography.fontFamily="${MAIN_FONT}" \
 --options.theme.typography.headings._fontFamily="${HEADING_FONT}" \
 --options.theme.typography.headings.fontWeight="${HEADING_FONT_WEIGHT}" \
---options.theme.colors.text.primary="${TEXT_COLOR}" \
---options.theme.colors.text.secondary="#505f7c" \
---options.theme.colors.success.main="#6bbd5b" \
---options.theme.colors.error.main="#ED6456" \
 --options.theme.spacing.sectionVertical="${VERTICAL_SPACING}" \
+--options.expandResponses="200,201,202" \
+--options.pathInMiddlePanel=1 \
 -t docs/openapi/resources/template.hbs || exit 1
 
-mv redoc-static.html docs/openapi/${SPEC_FILE/yaml/html}
-echo "--->" docs/openapi/${SPEC_FILE/yaml/html}
-
-if [[ ${OA_GENERATED} = 1 ]]; then
-    echo "--->" docs/openapi/${SPEC_FILE}
-    # Create TAR
-    tar -C ${PWD}/docs/openapi --exclude='./*.tar' --exclude='./.gitignore' --exclude='./resources' --exclude='./markdown' -jcf docs/openapi/${SPEC_FILE/yaml/tar} ./${SPEC_FILE} ./${SPEC_FILE/yaml/html}
-    echo "--->" docs/openapi/${SPEC_FILE/yaml/tar}
-fi
-
-# Example generating code:
-# openapi-generator generate -g go-server -i docs/openapi/paella-1.10.0-openapi.yaml -o ./codegen/go
+mv redoc-static.html ${SPEC_HTML_FILE}
 
 echo "DONE."
